# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import identitylayer_pb2 as identitylayer__pb2


class NonSecretServiceStub(object):
  """--------------------- SERVICES -----------------------

  `non-secret` services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddWalletRecord = channel.unary_unary(
        '/identitylayer.NonSecretService/AddWalletRecord',
        request_serializer=identitylayer__pb2.AddWalletRecordRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AddWalletRecordResponse.FromString,
        )
    self.UpdateWalletRecordValue = channel.unary_unary(
        '/identitylayer.NonSecretService/UpdateWalletRecordValue',
        request_serializer=identitylayer__pb2.UpdateWalletRecordValueRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.UpdateWalletRecordValueResponse.FromString,
        )
    self.UpdateWalletRecordTags = channel.unary_unary(
        '/identitylayer.NonSecretService/UpdateWalletRecordTags',
        request_serializer=identitylayer__pb2.UpdateWalletRecordTagsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.UpdateWalletRecordTagsResponse.FromString,
        )
    self.AddWalletRecordTags = channel.unary_unary(
        '/identitylayer.NonSecretService/AddWalletRecordTags',
        request_serializer=identitylayer__pb2.AddWalletRecordTagsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AddWalletRecordTagsResponse.FromString,
        )
    self.DeleteWalletRecordTags = channel.unary_unary(
        '/identitylayer.NonSecretService/DeleteWalletRecordTags',
        request_serializer=identitylayer__pb2.DeleteWalletRecordTagsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.DeleteWalletRecordTagsResponse.FromString,
        )
    self.DeleteWalletRecord = channel.unary_unary(
        '/identitylayer.NonSecretService/DeleteWalletRecord',
        request_serializer=identitylayer__pb2.DeleteWalletRecordRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.DeleteWalletRecordResponse.FromString,
        )
    self.GetWalletRecord = channel.unary_unary(
        '/identitylayer.NonSecretService/GetWalletRecord',
        request_serializer=identitylayer__pb2.GetWalletRecordRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.GetWalletRecordResponse.FromString,
        )
    self.OpenWalletSearch = channel.unary_unary(
        '/identitylayer.NonSecretService/OpenWalletSearch',
        request_serializer=identitylayer__pb2.OpenWalletSearchRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.OpenWalletSearchResponse.FromString,
        )
    self.FetchWalletSearchNextRecords = channel.unary_unary(
        '/identitylayer.NonSecretService/FetchWalletSearchNextRecords',
        request_serializer=identitylayer__pb2.FetchWalletSearchNextRecordsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.FetchWalletSearchNextRecordsResponse.FromString,
        )
    self.CloseWalletSearch = channel.unary_unary(
        '/identitylayer.NonSecretService/CloseWalletSearch',
        request_serializer=identitylayer__pb2.CloseWalletSearchRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CloseWalletSearchResponse.FromString,
        )


class NonSecretServiceServicer(object):
  """--------------------- SERVICES -----------------------

  `non-secret` services
  """

  def AddWalletRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateWalletRecordValue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateWalletRecordTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddWalletRecordTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteWalletRecordTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteWalletRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWalletRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenWalletSearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchWalletSearchNextRecords(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseWalletSearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NonSecretServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddWalletRecord': grpc.unary_unary_rpc_method_handler(
          servicer.AddWalletRecord,
          request_deserializer=identitylayer__pb2.AddWalletRecordRequest.FromString,
          response_serializer=identitylayer__pb2.AddWalletRecordResponse.SerializeToString,
      ),
      'UpdateWalletRecordValue': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateWalletRecordValue,
          request_deserializer=identitylayer__pb2.UpdateWalletRecordValueRequest.FromString,
          response_serializer=identitylayer__pb2.UpdateWalletRecordValueResponse.SerializeToString,
      ),
      'UpdateWalletRecordTags': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateWalletRecordTags,
          request_deserializer=identitylayer__pb2.UpdateWalletRecordTagsRequest.FromString,
          response_serializer=identitylayer__pb2.UpdateWalletRecordTagsResponse.SerializeToString,
      ),
      'AddWalletRecordTags': grpc.unary_unary_rpc_method_handler(
          servicer.AddWalletRecordTags,
          request_deserializer=identitylayer__pb2.AddWalletRecordTagsRequest.FromString,
          response_serializer=identitylayer__pb2.AddWalletRecordTagsResponse.SerializeToString,
      ),
      'DeleteWalletRecordTags': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteWalletRecordTags,
          request_deserializer=identitylayer__pb2.DeleteWalletRecordTagsRequest.FromString,
          response_serializer=identitylayer__pb2.DeleteWalletRecordTagsResponse.SerializeToString,
      ),
      'DeleteWalletRecord': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteWalletRecord,
          request_deserializer=identitylayer__pb2.DeleteWalletRecordRequest.FromString,
          response_serializer=identitylayer__pb2.DeleteWalletRecordResponse.SerializeToString,
      ),
      'GetWalletRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetWalletRecord,
          request_deserializer=identitylayer__pb2.GetWalletRecordRequest.FromString,
          response_serializer=identitylayer__pb2.GetWalletRecordResponse.SerializeToString,
      ),
      'OpenWalletSearch': grpc.unary_unary_rpc_method_handler(
          servicer.OpenWalletSearch,
          request_deserializer=identitylayer__pb2.OpenWalletSearchRequest.FromString,
          response_serializer=identitylayer__pb2.OpenWalletSearchResponse.SerializeToString,
      ),
      'FetchWalletSearchNextRecords': grpc.unary_unary_rpc_method_handler(
          servicer.FetchWalletSearchNextRecords,
          request_deserializer=identitylayer__pb2.FetchWalletSearchNextRecordsRequest.FromString,
          response_serializer=identitylayer__pb2.FetchWalletSearchNextRecordsResponse.SerializeToString,
      ),
      'CloseWalletSearch': grpc.unary_unary_rpc_method_handler(
          servicer.CloseWalletSearch,
          request_deserializer=identitylayer__pb2.CloseWalletSearchRequest.FromString,
          response_serializer=identitylayer__pb2.CloseWalletSearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.NonSecretService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class LedgerServiceStub(object):
  """`ledger` services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SignAndSubmitRequest = channel.unary_unary(
        '/identitylayer.LedgerService/SignAndSubmitRequest',
        request_serializer=identitylayer__pb2.SignAndSubmitRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.SignAndSubmitRequestRs.FromString,
        )
    self.SubmitRequest = channel.unary_unary(
        '/identitylayer.LedgerService/SubmitRequest',
        request_serializer=identitylayer__pb2.SubmitRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.SubmitRequestRs.FromString,
        )
    self.SubmitAction = channel.unary_unary(
        '/identitylayer.LedgerService/SubmitAction',
        request_serializer=identitylayer__pb2.SubmitActionRq.SerializeToString,
        response_deserializer=identitylayer__pb2.SubmitActionRs.FromString,
        )
    self.SignRequest = channel.unary_unary(
        '/identitylayer.LedgerService/SignRequest',
        request_serializer=identitylayer__pb2.SignRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.SignRequestRs.FromString,
        )
    self.MultiSignRequest = channel.unary_unary(
        '/identitylayer.LedgerService/MultiSignRequest',
        request_serializer=identitylayer__pb2.MultiSignRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.MultiSignRequestRs.FromString,
        )
    self.BuildGetDdoRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetDdoRequest',
        request_serializer=identitylayer__pb2.BuildGetDdoRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetDdoRequestRs.FromString,
        )
    self.BuildNymRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildNymRequest',
        request_serializer=identitylayer__pb2.BuildNymRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildNymRequestRs.FromString,
        )
    self.BuildAttribRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildAttribRequest',
        request_serializer=identitylayer__pb2.BuildAttribRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildAttribRequestRs.FromString,
        )
    self.BuildGetAttribRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetAttribRequest',
        request_serializer=identitylayer__pb2.BuildGetAttribRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetAttribRequestRs.FromString,
        )
    self.BuildGetNymRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetNymRequest',
        request_serializer=identitylayer__pb2.BuildGetNymRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetNymRequestRs.FromString,
        )
    self.BuildSchemaRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildSchemaRequest',
        request_serializer=identitylayer__pb2.BuildSchemaRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildSchemaRequestRs.FromString,
        )
    self.BuildGetSchemaRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetSchemaRequest',
        request_serializer=identitylayer__pb2.BuildGetSchemaRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetSchemaRequestRs.FromString,
        )
    self.ParseGetSchemaResponse = channel.unary_unary(
        '/identitylayer.LedgerService/ParseGetSchemaResponse',
        request_serializer=identitylayer__pb2.ParseGetSchemaResponseRq.SerializeToString,
        response_deserializer=identitylayer__pb2.ParseGetSchemaResponseRs.FromString,
        )
    self.BuildCredDefRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildCredDefRequest',
        request_serializer=identitylayer__pb2.BuildCredDefRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildCredDefRequestRs.FromString,
        )
    self.BuildGetCredDefRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetCredDefRequest',
        request_serializer=identitylayer__pb2.BuildGetCredDefRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetCredDefRequestRs.FromString,
        )
    self.ParseGetCredDefResponse = channel.unary_unary(
        '/identitylayer.LedgerService/ParseGetCredDefResponse',
        request_serializer=identitylayer__pb2.ParseGetCredDefResponseRq.SerializeToString,
        response_deserializer=identitylayer__pb2.ParseGetCredDefResponseRs.FromString,
        )
    self.BuildNodeRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildNodeRequest',
        request_serializer=identitylayer__pb2.BuildNodeRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildNodeRequestRs.FromString,
        )
    self.BuildGetValidatorInfoRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetValidatorInfoRequest',
        request_serializer=identitylayer__pb2.BuildGetValidatorInfoRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetValidatorInfoRequestRs.FromString,
        )
    self.BuildGetTxnRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetTxnRequest',
        request_serializer=identitylayer__pb2.BuildGetTxnRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetTxnRequestRs.FromString,
        )
    self.BuildPoolConfigRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildPoolConfigRequest',
        request_serializer=identitylayer__pb2.BuildPoolConfigRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildPoolConfigRequestRs.FromString,
        )
    self.BuildPoolRestartRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildPoolRestartRequest',
        request_serializer=identitylayer__pb2.BuildPoolRestartRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildPoolRestartRequestRs.FromString,
        )
    self.BuildPoolUpgradeRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildPoolUpgradeRequest',
        request_serializer=identitylayer__pb2.BuildPoolUpgradeRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildPoolUpgradeRequestRs.FromString,
        )
    self.BuildRevocRegDefRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildRevocRegDefRequest',
        request_serializer=identitylayer__pb2.BuildRevocRegDefRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildRevocRegDefRequestRs.FromString,
        )
    self.BuildGetRevocRegDefRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetRevocRegDefRequest',
        request_serializer=identitylayer__pb2.BuildGetRevocRegDefRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetRevocRegDefRequestRs.FromString,
        )
    self.ParseGetRevocRegDefResponse = channel.unary_unary(
        '/identitylayer.LedgerService/ParseGetRevocRegDefResponse',
        request_serializer=identitylayer__pb2.ParseGetRevocRegDefResponseRq.SerializeToString,
        response_deserializer=identitylayer__pb2.ParseGetRevocRegDefResponseRs.FromString,
        )
    self.BuildRevocRegEntryRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildRevocRegEntryRequest',
        request_serializer=identitylayer__pb2.BuildRevocRegEntryRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildRevocRegEntryRequestRs.FromString,
        )
    self.BuildGetRevocRegRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetRevocRegRequest',
        request_serializer=identitylayer__pb2.BuildGetRevocRegRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetRevocRegRequestRs.FromString,
        )
    self.ParseGetRevocRegResponse = channel.unary_unary(
        '/identitylayer.LedgerService/ParseGetRevocRegResponse',
        request_serializer=identitylayer__pb2.ParseGetRevocRegResponseRq.SerializeToString,
        response_deserializer=identitylayer__pb2.ParseGetRevocRegResponseRs.FromString,
        )
    self.BuildGetRevocRegDeltaRequest = channel.unary_unary(
        '/identitylayer.LedgerService/BuildGetRevocRegDeltaRequest',
        request_serializer=identitylayer__pb2.BuildGetRevocRegDeltaRequestRq.SerializeToString,
        response_deserializer=identitylayer__pb2.BuildGetRevocRegDeltaRequestRs.FromString,
        )
    self.ParseGetRevocRegDeltaResponse = channel.unary_unary(
        '/identitylayer.LedgerService/ParseGetRevocRegDeltaResponse',
        request_serializer=identitylayer__pb2.ParseGetRevocRegDeltaResponseRq.SerializeToString,
        response_deserializer=identitylayer__pb2.ParseGetRevocRegDeltaResponseRs.FromString,
        )
    self.GetResponseMetadata = channel.unary_unary(
        '/identitylayer.LedgerService/GetResponseMetadata',
        request_serializer=identitylayer__pb2.GetResponseMetadataRq.SerializeToString,
        response_deserializer=identitylayer__pb2.GetResponseMetadataRs.FromString,
        )


class LedgerServiceServicer(object):
  """`ledger` services
  """

  def SignAndSubmitRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MultiSignRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetDdoRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildNymRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildAttribRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetAttribRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetNymRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildSchemaRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetSchemaRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParseGetSchemaResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildCredDefRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetCredDefRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParseGetCredDefResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildNodeRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetValidatorInfoRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetTxnRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildPoolConfigRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildPoolRestartRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildPoolUpgradeRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildRevocRegDefRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetRevocRegDefRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParseGetRevocRegDefResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildRevocRegEntryRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetRevocRegRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParseGetRevocRegResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildGetRevocRegDeltaRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ParseGetRevocRegDeltaResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetResponseMetadata(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LedgerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SignAndSubmitRequest': grpc.unary_unary_rpc_method_handler(
          servicer.SignAndSubmitRequest,
          request_deserializer=identitylayer__pb2.SignAndSubmitRequestRq.FromString,
          response_serializer=identitylayer__pb2.SignAndSubmitRequestRs.SerializeToString,
      ),
      'SubmitRequest': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitRequest,
          request_deserializer=identitylayer__pb2.SubmitRequestRq.FromString,
          response_serializer=identitylayer__pb2.SubmitRequestRs.SerializeToString,
      ),
      'SubmitAction': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitAction,
          request_deserializer=identitylayer__pb2.SubmitActionRq.FromString,
          response_serializer=identitylayer__pb2.SubmitActionRs.SerializeToString,
      ),
      'SignRequest': grpc.unary_unary_rpc_method_handler(
          servicer.SignRequest,
          request_deserializer=identitylayer__pb2.SignRequestRq.FromString,
          response_serializer=identitylayer__pb2.SignRequestRs.SerializeToString,
      ),
      'MultiSignRequest': grpc.unary_unary_rpc_method_handler(
          servicer.MultiSignRequest,
          request_deserializer=identitylayer__pb2.MultiSignRequestRq.FromString,
          response_serializer=identitylayer__pb2.MultiSignRequestRs.SerializeToString,
      ),
      'BuildGetDdoRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetDdoRequest,
          request_deserializer=identitylayer__pb2.BuildGetDdoRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetDdoRequestRs.SerializeToString,
      ),
      'BuildNymRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildNymRequest,
          request_deserializer=identitylayer__pb2.BuildNymRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildNymRequestRs.SerializeToString,
      ),
      'BuildAttribRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildAttribRequest,
          request_deserializer=identitylayer__pb2.BuildAttribRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildAttribRequestRs.SerializeToString,
      ),
      'BuildGetAttribRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetAttribRequest,
          request_deserializer=identitylayer__pb2.BuildGetAttribRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetAttribRequestRs.SerializeToString,
      ),
      'BuildGetNymRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetNymRequest,
          request_deserializer=identitylayer__pb2.BuildGetNymRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetNymRequestRs.SerializeToString,
      ),
      'BuildSchemaRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildSchemaRequest,
          request_deserializer=identitylayer__pb2.BuildSchemaRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildSchemaRequestRs.SerializeToString,
      ),
      'BuildGetSchemaRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetSchemaRequest,
          request_deserializer=identitylayer__pb2.BuildGetSchemaRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetSchemaRequestRs.SerializeToString,
      ),
      'ParseGetSchemaResponse': grpc.unary_unary_rpc_method_handler(
          servicer.ParseGetSchemaResponse,
          request_deserializer=identitylayer__pb2.ParseGetSchemaResponseRq.FromString,
          response_serializer=identitylayer__pb2.ParseGetSchemaResponseRs.SerializeToString,
      ),
      'BuildCredDefRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildCredDefRequest,
          request_deserializer=identitylayer__pb2.BuildCredDefRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildCredDefRequestRs.SerializeToString,
      ),
      'BuildGetCredDefRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetCredDefRequest,
          request_deserializer=identitylayer__pb2.BuildGetCredDefRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetCredDefRequestRs.SerializeToString,
      ),
      'ParseGetCredDefResponse': grpc.unary_unary_rpc_method_handler(
          servicer.ParseGetCredDefResponse,
          request_deserializer=identitylayer__pb2.ParseGetCredDefResponseRq.FromString,
          response_serializer=identitylayer__pb2.ParseGetCredDefResponseRs.SerializeToString,
      ),
      'BuildNodeRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildNodeRequest,
          request_deserializer=identitylayer__pb2.BuildNodeRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildNodeRequestRs.SerializeToString,
      ),
      'BuildGetValidatorInfoRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetValidatorInfoRequest,
          request_deserializer=identitylayer__pb2.BuildGetValidatorInfoRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetValidatorInfoRequestRs.SerializeToString,
      ),
      'BuildGetTxnRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetTxnRequest,
          request_deserializer=identitylayer__pb2.BuildGetTxnRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetTxnRequestRs.SerializeToString,
      ),
      'BuildPoolConfigRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildPoolConfigRequest,
          request_deserializer=identitylayer__pb2.BuildPoolConfigRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildPoolConfigRequestRs.SerializeToString,
      ),
      'BuildPoolRestartRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildPoolRestartRequest,
          request_deserializer=identitylayer__pb2.BuildPoolRestartRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildPoolRestartRequestRs.SerializeToString,
      ),
      'BuildPoolUpgradeRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildPoolUpgradeRequest,
          request_deserializer=identitylayer__pb2.BuildPoolUpgradeRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildPoolUpgradeRequestRs.SerializeToString,
      ),
      'BuildRevocRegDefRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildRevocRegDefRequest,
          request_deserializer=identitylayer__pb2.BuildRevocRegDefRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildRevocRegDefRequestRs.SerializeToString,
      ),
      'BuildGetRevocRegDefRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetRevocRegDefRequest,
          request_deserializer=identitylayer__pb2.BuildGetRevocRegDefRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetRevocRegDefRequestRs.SerializeToString,
      ),
      'ParseGetRevocRegDefResponse': grpc.unary_unary_rpc_method_handler(
          servicer.ParseGetRevocRegDefResponse,
          request_deserializer=identitylayer__pb2.ParseGetRevocRegDefResponseRq.FromString,
          response_serializer=identitylayer__pb2.ParseGetRevocRegDefResponseRs.SerializeToString,
      ),
      'BuildRevocRegEntryRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildRevocRegEntryRequest,
          request_deserializer=identitylayer__pb2.BuildRevocRegEntryRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildRevocRegEntryRequestRs.SerializeToString,
      ),
      'BuildGetRevocRegRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetRevocRegRequest,
          request_deserializer=identitylayer__pb2.BuildGetRevocRegRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetRevocRegRequestRs.SerializeToString,
      ),
      'ParseGetRevocRegResponse': grpc.unary_unary_rpc_method_handler(
          servicer.ParseGetRevocRegResponse,
          request_deserializer=identitylayer__pb2.ParseGetRevocRegResponseRq.FromString,
          response_serializer=identitylayer__pb2.ParseGetRevocRegResponseRs.SerializeToString,
      ),
      'BuildGetRevocRegDeltaRequest': grpc.unary_unary_rpc_method_handler(
          servicer.BuildGetRevocRegDeltaRequest,
          request_deserializer=identitylayer__pb2.BuildGetRevocRegDeltaRequestRq.FromString,
          response_serializer=identitylayer__pb2.BuildGetRevocRegDeltaRequestRs.SerializeToString,
      ),
      'ParseGetRevocRegDeltaResponse': grpc.unary_unary_rpc_method_handler(
          servicer.ParseGetRevocRegDeltaResponse,
          request_deserializer=identitylayer__pb2.ParseGetRevocRegDeltaResponseRq.FromString,
          response_serializer=identitylayer__pb2.ParseGetRevocRegDeltaResponseRs.SerializeToString,
      ),
      'GetResponseMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetResponseMetadata,
          request_deserializer=identitylayer__pb2.GetResponseMetadataRq.FromString,
          response_serializer=identitylayer__pb2.GetResponseMetadataRs.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.LedgerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DidServiceStub(object):
  """`did` Services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAndStoreMyDid = channel.unary_unary(
        '/identitylayer.DidService/CreateAndStoreMyDid',
        request_serializer=identitylayer__pb2.CreateAndStoreMyDidRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CreateAndStoreMyDidResponse.FromString,
        )
    self.ReplaceKeysStart = channel.unary_unary(
        '/identitylayer.DidService/ReplaceKeysStart',
        request_serializer=identitylayer__pb2.ReplaceKeysStartRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ReplaceKeysStartResponse.FromString,
        )
    self.ReplaceKeysApply = channel.unary_unary(
        '/identitylayer.DidService/ReplaceKeysApply',
        request_serializer=identitylayer__pb2.ReplaceKeysApplyRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ReplaceKeysApplyResponse.FromString,
        )
    self.StoreTheirDid = channel.unary_unary(
        '/identitylayer.DidService/StoreTheirDid',
        request_serializer=identitylayer__pb2.StoreTheirDidRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.StoreTheirDidResponse.FromString,
        )
    self.DidCreateKey = channel.unary_unary(
        '/identitylayer.DidService/DidCreateKey',
        request_serializer=identitylayer__pb2.DidCreateKeyRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.DidCreateKeyResponse.FromString,
        )
    self.DidSetKeyMetadata = channel.unary_unary(
        '/identitylayer.DidService/DidSetKeyMetadata',
        request_serializer=identitylayer__pb2.DidSetKeyMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.DidSetKeyMetadataRequest.FromString,
        )
    self.DidGetKeyMetadata = channel.unary_unary(
        '/identitylayer.DidService/DidGetKeyMetadata',
        request_serializer=identitylayer__pb2.DidGetKeyMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.DidGetKeyMetadataResponse.FromString,
        )
    self.KeyForDid = channel.unary_unary(
        '/identitylayer.DidService/KeyForDid',
        request_serializer=identitylayer__pb2.KeyForDidRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.KeyForDidResponse.FromString,
        )
    self.KeyForLocalDid = channel.unary_unary(
        '/identitylayer.DidService/KeyForLocalDid',
        request_serializer=identitylayer__pb2.KeyForLocalDidRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.KeyForLocalDidResponse.FromString,
        )
    self.SetEndpointForDid = channel.unary_unary(
        '/identitylayer.DidService/SetEndpointForDid',
        request_serializer=identitylayer__pb2.SetEndpointForDidRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.SetEndpointForDidResponse.FromString,
        )
    self.GetEndpointForDid = channel.unary_unary(
        '/identitylayer.DidService/GetEndpointForDid',
        request_serializer=identitylayer__pb2.GetEndpointForDidRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.GetEndpointForDidResponse.FromString,
        )
    self.SetDidMetadata = channel.unary_unary(
        '/identitylayer.DidService/SetDidMetadata',
        request_serializer=identitylayer__pb2.SetDidMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.SetDidMetadataResponse.FromString,
        )
    self.GetDidMetadata = channel.unary_unary(
        '/identitylayer.DidService/GetDidMetadata',
        request_serializer=identitylayer__pb2.GetDidMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.GetDidMetadataResponse.FromString,
        )
    self.GetMyDidWithMeta = channel.unary_unary(
        '/identitylayer.DidService/GetMyDidWithMeta',
        request_serializer=identitylayer__pb2.GetMyDidWithMetaRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.GetMyDidWithMetaResponse.FromString,
        )
    self.ListMyDidsWithMeta = channel.unary_unary(
        '/identitylayer.DidService/ListMyDidsWithMeta',
        request_serializer=identitylayer__pb2.ListMyDidsWithMetaRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ListMyDidsWithMetaResponse.FromString,
        )
    self.AbbreviateVerkey = channel.unary_unary(
        '/identitylayer.DidService/AbbreviateVerkey',
        request_serializer=identitylayer__pb2.AbbreviateVerkeyRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AbbreviateVerkeyResponse.FromString,
        )


class DidServiceServicer(object):
  """`did` Services
  """

  def CreateAndStoreMyDid(self, request, context):
    """Create And Store My Did
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplaceKeysStart(self, request, context):
    """Replace Keys Start
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplaceKeysApply(self, request, context):
    """Replace Keys Apply
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StoreTheirDid(self, request, context):
    """Store Their Did
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DidCreateKey(self, request, context):
    """Create Key; Prefix 'Did' to avoid conflict with other proto
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DidSetKeyMetadata(self, request, context):
    """Set Key Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DidGetKeyMetadata(self, request, context):
    """Get Key Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def KeyForDid(self, request, context):
    """Key For Did
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def KeyForLocalDid(self, request, context):
    """Key For Local Did
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetEndpointForDid(self, request, context):
    """Set Endpoint For Did
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEndpointForDid(self, request, context):
    """Get Endpoint For Did
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDidMetadata(self, request, context):
    """Set Did Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDidMetadata(self, request, context):
    """Get Did Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyDidWithMeta(self, request, context):
    """Get My Did With Meta
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListMyDidsWithMeta(self, request, context):
    """List My Dids With Meta
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AbbreviateVerkey(self, request, context):
    """Abbreviate Verkey
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DidServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAndStoreMyDid': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAndStoreMyDid,
          request_deserializer=identitylayer__pb2.CreateAndStoreMyDidRequest.FromString,
          response_serializer=identitylayer__pb2.CreateAndStoreMyDidResponse.SerializeToString,
      ),
      'ReplaceKeysStart': grpc.unary_unary_rpc_method_handler(
          servicer.ReplaceKeysStart,
          request_deserializer=identitylayer__pb2.ReplaceKeysStartRequest.FromString,
          response_serializer=identitylayer__pb2.ReplaceKeysStartResponse.SerializeToString,
      ),
      'ReplaceKeysApply': grpc.unary_unary_rpc_method_handler(
          servicer.ReplaceKeysApply,
          request_deserializer=identitylayer__pb2.ReplaceKeysApplyRequest.FromString,
          response_serializer=identitylayer__pb2.ReplaceKeysApplyResponse.SerializeToString,
      ),
      'StoreTheirDid': grpc.unary_unary_rpc_method_handler(
          servicer.StoreTheirDid,
          request_deserializer=identitylayer__pb2.StoreTheirDidRequest.FromString,
          response_serializer=identitylayer__pb2.StoreTheirDidResponse.SerializeToString,
      ),
      'DidCreateKey': grpc.unary_unary_rpc_method_handler(
          servicer.DidCreateKey,
          request_deserializer=identitylayer__pb2.DidCreateKeyRequest.FromString,
          response_serializer=identitylayer__pb2.DidCreateKeyResponse.SerializeToString,
      ),
      'DidSetKeyMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.DidSetKeyMetadata,
          request_deserializer=identitylayer__pb2.DidSetKeyMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.DidSetKeyMetadataRequest.SerializeToString,
      ),
      'DidGetKeyMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.DidGetKeyMetadata,
          request_deserializer=identitylayer__pb2.DidGetKeyMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.DidGetKeyMetadataResponse.SerializeToString,
      ),
      'KeyForDid': grpc.unary_unary_rpc_method_handler(
          servicer.KeyForDid,
          request_deserializer=identitylayer__pb2.KeyForDidRequest.FromString,
          response_serializer=identitylayer__pb2.KeyForDidResponse.SerializeToString,
      ),
      'KeyForLocalDid': grpc.unary_unary_rpc_method_handler(
          servicer.KeyForLocalDid,
          request_deserializer=identitylayer__pb2.KeyForLocalDidRequest.FromString,
          response_serializer=identitylayer__pb2.KeyForLocalDidResponse.SerializeToString,
      ),
      'SetEndpointForDid': grpc.unary_unary_rpc_method_handler(
          servicer.SetEndpointForDid,
          request_deserializer=identitylayer__pb2.SetEndpointForDidRequest.FromString,
          response_serializer=identitylayer__pb2.SetEndpointForDidResponse.SerializeToString,
      ),
      'GetEndpointForDid': grpc.unary_unary_rpc_method_handler(
          servicer.GetEndpointForDid,
          request_deserializer=identitylayer__pb2.GetEndpointForDidRequest.FromString,
          response_serializer=identitylayer__pb2.GetEndpointForDidResponse.SerializeToString,
      ),
      'SetDidMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.SetDidMetadata,
          request_deserializer=identitylayer__pb2.SetDidMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.SetDidMetadataResponse.SerializeToString,
      ),
      'GetDidMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetDidMetadata,
          request_deserializer=identitylayer__pb2.GetDidMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.GetDidMetadataResponse.SerializeToString,
      ),
      'GetMyDidWithMeta': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyDidWithMeta,
          request_deserializer=identitylayer__pb2.GetMyDidWithMetaRequest.FromString,
          response_serializer=identitylayer__pb2.GetMyDidWithMetaResponse.SerializeToString,
      ),
      'ListMyDidsWithMeta': grpc.unary_unary_rpc_method_handler(
          servicer.ListMyDidsWithMeta,
          request_deserializer=identitylayer__pb2.ListMyDidsWithMetaRequest.FromString,
          response_serializer=identitylayer__pb2.ListMyDidsWithMetaResponse.SerializeToString,
      ),
      'AbbreviateVerkey': grpc.unary_unary_rpc_method_handler(
          servicer.AbbreviateVerkey,
          request_deserializer=identitylayer__pb2.AbbreviateVerkeyRequest.FromString,
          response_serializer=identitylayer__pb2.AbbreviateVerkeyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.DidService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PairwiseServiceStub(object):
  """`pairwise` Services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IsPairwiseExists = channel.unary_unary(
        '/identitylayer.PairwiseService/IsPairwiseExists',
        request_serializer=identitylayer__pb2.IsPairwiseExistsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IsPairwiseExistsResponse.FromString,
        )
    self.CreatePairwise = channel.unary_unary(
        '/identitylayer.PairwiseService/CreatePairwise',
        request_serializer=identitylayer__pb2.CreatePairwiseRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CreatePairwiseResponse.FromString,
        )
    self.ListPairwise = channel.unary_unary(
        '/identitylayer.PairwiseService/ListPairwise',
        request_serializer=identitylayer__pb2.ListPairwiseRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ListPairwiseResponse.FromString,
        )
    self.GetPairwise = channel.unary_unary(
        '/identitylayer.PairwiseService/GetPairwise',
        request_serializer=identitylayer__pb2.GetPairwiseRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.GetPairwiseResponse.FromString,
        )
    self.SetPairwiseMetadata = channel.unary_unary(
        '/identitylayer.PairwiseService/SetPairwiseMetadata',
        request_serializer=identitylayer__pb2.SetPairwiseMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.SetPairwiseMetadataResponse.FromString,
        )


class PairwiseServiceServicer(object):
  """`pairwise` Services
  """

  def IsPairwiseExists(self, request, context):
    """Is Pairwise Exists
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePairwise(self, request, context):
    """Create Pairwise
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPairwise(self, request, context):
    """List Pairwise
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPairwise(self, request, context):
    """Get Pairwise
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPairwiseMetadata(self, request, context):
    """Set Pairwise Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PairwiseServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IsPairwiseExists': grpc.unary_unary_rpc_method_handler(
          servicer.IsPairwiseExists,
          request_deserializer=identitylayer__pb2.IsPairwiseExistsRequest.FromString,
          response_serializer=identitylayer__pb2.IsPairwiseExistsResponse.SerializeToString,
      ),
      'CreatePairwise': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePairwise,
          request_deserializer=identitylayer__pb2.CreatePairwiseRequest.FromString,
          response_serializer=identitylayer__pb2.CreatePairwiseResponse.SerializeToString,
      ),
      'ListPairwise': grpc.unary_unary_rpc_method_handler(
          servicer.ListPairwise,
          request_deserializer=identitylayer__pb2.ListPairwiseRequest.FromString,
          response_serializer=identitylayer__pb2.ListPairwiseResponse.SerializeToString,
      ),
      'GetPairwise': grpc.unary_unary_rpc_method_handler(
          servicer.GetPairwise,
          request_deserializer=identitylayer__pb2.GetPairwiseRequest.FromString,
          response_serializer=identitylayer__pb2.GetPairwiseResponse.SerializeToString,
      ),
      'SetPairwiseMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.SetPairwiseMetadata,
          request_deserializer=identitylayer__pb2.SetPairwiseMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.SetPairwiseMetadataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.PairwiseService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CryptoServiceStub(object):
  """`crypto` Services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateKey = channel.unary_unary(
        '/identitylayer.CryptoService/CreateKey',
        request_serializer=identitylayer__pb2.CreateKeyRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CreateKeyResponse.FromString,
        )
    self.SetKeyMetadata = channel.unary_unary(
        '/identitylayer.CryptoService/SetKeyMetadata',
        request_serializer=identitylayer__pb2.SetKeyMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.SetKeyMetadataResponse.FromString,
        )
    self.GetKeyMetadata = channel.unary_unary(
        '/identitylayer.CryptoService/GetKeyMetadata',
        request_serializer=identitylayer__pb2.GetKeyMetadataRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.GetKeyMetadataResponse.FromString,
        )
    self.CryptoSign = channel.unary_unary(
        '/identitylayer.CryptoService/CryptoSign',
        request_serializer=identitylayer__pb2.CryptoSignRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CryptoSignResponse.FromString,
        )
    self.CryptoVerify = channel.unary_unary(
        '/identitylayer.CryptoService/CryptoVerify',
        request_serializer=identitylayer__pb2.CryptoVerifyRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CryptoVerifyResponse.FromString,
        )
    self.AuthCrypt = channel.unary_unary(
        '/identitylayer.CryptoService/AuthCrypt',
        request_serializer=identitylayer__pb2.AuthCryptRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AuthCryptResponse.FromString,
        )
    self.AuthDecrypt = channel.unary_unary(
        '/identitylayer.CryptoService/AuthDecrypt',
        request_serializer=identitylayer__pb2.AuthDecryptRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AuthDecryptResponse.FromString,
        )
    self.AnonCrypt = channel.unary_unary(
        '/identitylayer.CryptoService/AnonCrypt',
        request_serializer=identitylayer__pb2.AnonCryptRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AnonCryptResponse.FromString,
        )
    self.AnonDecrypt = channel.unary_unary(
        '/identitylayer.CryptoService/AnonDecrypt',
        request_serializer=identitylayer__pb2.AnonDecryptRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.AnonDecryptResponse.FromString,
        )


class CryptoServiceServicer(object):
  """`crypto` Services
  """

  def CreateKey(self, request, context):
    """Create Key
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetKeyMetadata(self, request, context):
    """Set Key Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKeyMetadata(self, request, context):
    """Get Key Metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CryptoSign(self, request, context):
    """Crypto Sign
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CryptoVerify(self, request, context):
    """Crypto Verify
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthCrypt(self, request, context):
    """Auth Crypt
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDecrypt(self, request, context):
    """Auth Decrypt
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnonCrypt(self, request, context):
    """Anon Crypt
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnonDecrypt(self, request, context):
    """Anon Decrypt
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CryptoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateKey': grpc.unary_unary_rpc_method_handler(
          servicer.CreateKey,
          request_deserializer=identitylayer__pb2.CreateKeyRequest.FromString,
          response_serializer=identitylayer__pb2.CreateKeyResponse.SerializeToString,
      ),
      'SetKeyMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.SetKeyMetadata,
          request_deserializer=identitylayer__pb2.SetKeyMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.SetKeyMetadataResponse.SerializeToString,
      ),
      'GetKeyMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetKeyMetadata,
          request_deserializer=identitylayer__pb2.GetKeyMetadataRequest.FromString,
          response_serializer=identitylayer__pb2.GetKeyMetadataResponse.SerializeToString,
      ),
      'CryptoSign': grpc.unary_unary_rpc_method_handler(
          servicer.CryptoSign,
          request_deserializer=identitylayer__pb2.CryptoSignRequest.FromString,
          response_serializer=identitylayer__pb2.CryptoSignResponse.SerializeToString,
      ),
      'CryptoVerify': grpc.unary_unary_rpc_method_handler(
          servicer.CryptoVerify,
          request_deserializer=identitylayer__pb2.CryptoVerifyRequest.FromString,
          response_serializer=identitylayer__pb2.CryptoVerifyResponse.SerializeToString,
      ),
      'AuthCrypt': grpc.unary_unary_rpc_method_handler(
          servicer.AuthCrypt,
          request_deserializer=identitylayer__pb2.AuthCryptRequest.FromString,
          response_serializer=identitylayer__pb2.AuthCryptResponse.SerializeToString,
      ),
      'AuthDecrypt': grpc.unary_unary_rpc_method_handler(
          servicer.AuthDecrypt,
          request_deserializer=identitylayer__pb2.AuthDecryptRequest.FromString,
          response_serializer=identitylayer__pb2.AuthDecryptResponse.SerializeToString,
      ),
      'AnonCrypt': grpc.unary_unary_rpc_method_handler(
          servicer.AnonCrypt,
          request_deserializer=identitylayer__pb2.AnonCryptRequest.FromString,
          response_serializer=identitylayer__pb2.AnonCryptResponse.SerializeToString,
      ),
      'AnonDecrypt': grpc.unary_unary_rpc_method_handler(
          servicer.AnonDecrypt,
          request_deserializer=identitylayer__pb2.AnonDecryptRequest.FromString,
          response_serializer=identitylayer__pb2.AnonDecryptResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.CryptoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PoolServiceStub(object):
  """`pool` Services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreatePoolLedgerConfig = channel.unary_unary(
        '/identitylayer.PoolService/CreatePoolLedgerConfig',
        request_serializer=identitylayer__pb2.CreatePoolLedgerConfigRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CreatePoolLedgerConfigResponse.FromString,
        )
    self.OpenPoolLedger = channel.unary_unary(
        '/identitylayer.PoolService/OpenPoolLedger',
        request_serializer=identitylayer__pb2.OpenPoolLedgerRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.OpenPoolLedgerResponse.FromString,
        )
    self.RefreshPoolLedger = channel.unary_unary(
        '/identitylayer.PoolService/RefreshPoolLedger',
        request_serializer=identitylayer__pb2.RefreshPoolLedgerRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.RefreshPoolLedgerResponse.FromString,
        )
    self.ListPools = channel.unary_unary(
        '/identitylayer.PoolService/ListPools',
        request_serializer=identitylayer__pb2.ListPoolsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ListPoolsResponse.FromString,
        )
    self.ClosePoolLedger = channel.unary_unary(
        '/identitylayer.PoolService/ClosePoolLedger',
        request_serializer=identitylayer__pb2.ClosePoolLedgerRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ClosePoolLedgerResponse.FromString,
        )
    self.DeletePoolLedgerConfig = channel.unary_unary(
        '/identitylayer.PoolService/DeletePoolLedgerConfig',
        request_serializer=identitylayer__pb2.DeletePoolLedgerConfigRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.DeletePoolLedgerConfigResponse.FromString,
        )
    self.SetProtocolVersion = channel.unary_unary(
        '/identitylayer.PoolService/SetProtocolVersion',
        request_serializer=identitylayer__pb2.SetProtocolVersionRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.SetProtocolVersionResponse.FromString,
        )


class PoolServiceServicer(object):
  """`pool` Services
  """

  def CreatePoolLedgerConfig(self, request, context):
    """Create Pool Ledger Config
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenPoolLedger(self, request, context):
    """Open Pool Ledger
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RefreshPoolLedger(self, request, context):
    """Refresh Pool Ledger
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPools(self, request, context):
    """List Pools
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClosePoolLedger(self, request, context):
    """Close Pool Ledger
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePoolLedgerConfig(self, request, context):
    """Delete Pool Ledger Config
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetProtocolVersion(self, request, context):
    """Set Protocol Version
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PoolServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreatePoolLedgerConfig': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePoolLedgerConfig,
          request_deserializer=identitylayer__pb2.CreatePoolLedgerConfigRequest.FromString,
          response_serializer=identitylayer__pb2.CreatePoolLedgerConfigResponse.SerializeToString,
      ),
      'OpenPoolLedger': grpc.unary_unary_rpc_method_handler(
          servicer.OpenPoolLedger,
          request_deserializer=identitylayer__pb2.OpenPoolLedgerRequest.FromString,
          response_serializer=identitylayer__pb2.OpenPoolLedgerResponse.SerializeToString,
      ),
      'RefreshPoolLedger': grpc.unary_unary_rpc_method_handler(
          servicer.RefreshPoolLedger,
          request_deserializer=identitylayer__pb2.RefreshPoolLedgerRequest.FromString,
          response_serializer=identitylayer__pb2.RefreshPoolLedgerResponse.SerializeToString,
      ),
      'ListPools': grpc.unary_unary_rpc_method_handler(
          servicer.ListPools,
          request_deserializer=identitylayer__pb2.ListPoolsRequest.FromString,
          response_serializer=identitylayer__pb2.ListPoolsResponse.SerializeToString,
      ),
      'ClosePoolLedger': grpc.unary_unary_rpc_method_handler(
          servicer.ClosePoolLedger,
          request_deserializer=identitylayer__pb2.ClosePoolLedgerRequest.FromString,
          response_serializer=identitylayer__pb2.ClosePoolLedgerResponse.SerializeToString,
      ),
      'DeletePoolLedgerConfig': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePoolLedgerConfig,
          request_deserializer=identitylayer__pb2.DeletePoolLedgerConfigRequest.FromString,
          response_serializer=identitylayer__pb2.DeletePoolLedgerConfigResponse.SerializeToString,
      ),
      'SetProtocolVersion': grpc.unary_unary_rpc_method_handler(
          servicer.SetProtocolVersion,
          request_deserializer=identitylayer__pb2.SetProtocolVersionRequest.FromString,
          response_serializer=identitylayer__pb2.SetProtocolVersionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.PoolService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AnoncredsServiceStub(object):
  """`anoncreds` Services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IssuerCreateSchema = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerCreateSchema',
        request_serializer=identitylayer__pb2.IssuerCreateSchemaRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerCreateSchemaResponse.FromString,
        )
    self.IssuerCreateAndStoreCredentialDef = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerCreateAndStoreCredentialDef',
        request_serializer=identitylayer__pb2.IssuerCreateAndStoreCredentialDefRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerCreateAndStoreCredentialDefResponse.FromString,
        )
    self.IssuerCreateAndStoreRevocReg = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerCreateAndStoreRevocReg',
        request_serializer=identitylayer__pb2.IssuerCreateAndStoreRevocRegRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerCreateAndStoreRevocRegResponse.FromString,
        )
    self.IssuerCreateCredentialOffer = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerCreateCredentialOffer',
        request_serializer=identitylayer__pb2.IssuerCreateCredentialOfferRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerCreateCredentialOfferResponse.FromString,
        )
    self.IssuerCreateCredential = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerCreateCredential',
        request_serializer=identitylayer__pb2.IssuerCreateCredentialRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerCreateCredentialResponse.FromString,
        )
    self.IssuerRevokeCredential = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerRevokeCredential',
        request_serializer=identitylayer__pb2.IssuerRevokeCredentialRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerRevokeCredentialResponse.FromString,
        )
    self.IssuerMergeRevocationRegistryDeltas = channel.unary_unary(
        '/identitylayer.AnoncredsService/IssuerMergeRevocationRegistryDeltas',
        request_serializer=identitylayer__pb2.IssuerMergeRevocationRegistryDeltasRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.IssuerMergeRevocationRegistryDeltasResponse.FromString,
        )
    self.ProverCreateMasterSecret = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverCreateMasterSecret',
        request_serializer=identitylayer__pb2.ProverCreateMasterSecretRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverCreateMasterSecretResponse.FromString,
        )
    self.ProverCreateCredentialReq = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverCreateCredentialReq',
        request_serializer=identitylayer__pb2.ProverCreateCredentialReqRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverCreateCredentialReqResponse.FromString,
        )
    self.ProverStoreCredential = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverStoreCredential',
        request_serializer=identitylayer__pb2.ProverStoreCredentialRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverStoreCredentialResponse.FromString,
        )
    self.ProverGetCredential = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverGetCredential',
        request_serializer=identitylayer__pb2.ProverGetCredentialRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverGetCredentialResponse.FromString,
        )
    self.ProverGetCredentials = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverGetCredentials',
        request_serializer=identitylayer__pb2.ProverGetCredentialsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverGetCredentialsResponse.FromString,
        )
    self.ProverSeachCredentials = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverSeachCredentials',
        request_serializer=identitylayer__pb2.ProverSeachCredentialsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverSeachCredentialsResponse.FromString,
        )
    self.ProverFetchCredentials = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverFetchCredentials',
        request_serializer=identitylayer__pb2.ProverFetchCredentialsRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverFetchCredentialsResponse.FromString,
        )
    self.ProverCloseCredentialsSearch = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverCloseCredentialsSearch',
        request_serializer=identitylayer__pb2.ProverCloseCredentialsSearchRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverCloseCredentialsSearchResponse.FromString,
        )
    self.ProverGetCredentialsForProofReq = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverGetCredentialsForProofReq',
        request_serializer=identitylayer__pb2.ProverGetCredentialsForProofReqRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverGetCredentialsForProofReqResponse.FromString,
        )
    self.ProverSearchCredentialsForProofReq = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverSearchCredentialsForProofReq',
        request_serializer=identitylayer__pb2.ProverSearchCredentialsForProofReqRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverSearchCredentialsForProofReqResponse.FromString,
        )
    self.ProverFetchCredentialsForProofReq = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverFetchCredentialsForProofReq',
        request_serializer=identitylayer__pb2.ProverFetchCredentialsForProofReqRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverFetchCredentialsForProofReqResponse.FromString,
        )
    self.ProverCloseCredentialsSearchForProofReq = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverCloseCredentialsSearchForProofReq',
        request_serializer=identitylayer__pb2.ProverCloseCredentialsSearchForProofReqRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverCloseCredentialsSearchForProofReqResponse.FromString,
        )
    self.ProverCreateProof = channel.unary_unary(
        '/identitylayer.AnoncredsService/ProverCreateProof',
        request_serializer=identitylayer__pb2.ProverCreateProofRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.ProverCreateProofResponse.FromString,
        )
    self.VerifierVerifyProof = channel.unary_unary(
        '/identitylayer.AnoncredsService/VerifierVerifyProof',
        request_serializer=identitylayer__pb2.VerifierVerifyProofRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.VerifierVerifyProofResponse.FromString,
        )
    self.CreateRevocationState = channel.unary_unary(
        '/identitylayer.AnoncredsService/CreateRevocationState',
        request_serializer=identitylayer__pb2.CreateRevocationStateRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.CreateRevocationStateResponse.FromString,
        )
    self.UpdateRevocationState = channel.unary_unary(
        '/identitylayer.AnoncredsService/UpdateRevocationState',
        request_serializer=identitylayer__pb2.UpdateRevocationStateRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.UpdateRevocationStateResponse.FromString,
        )


class AnoncredsServiceServicer(object):
  """`anoncreds` Services
  """

  def IssuerCreateSchema(self, request, context):
    """Issuer Create Schema
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IssuerCreateAndStoreCredentialDef(self, request, context):
    """issuer create and store credential def
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IssuerCreateAndStoreRevocReg(self, request, context):
    """Issuer Create And Store Revoc Reg
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IssuerCreateCredentialOffer(self, request, context):
    """Issuer Create Credential Offer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IssuerCreateCredential(self, request, context):
    """Issuer Create Credential
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IssuerRevokeCredential(self, request, context):
    """Issuer Revoke Credential
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IssuerMergeRevocationRegistryDeltas(self, request, context):
    """Issuer Merge Revocation Registry Deltas
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverCreateMasterSecret(self, request, context):
    """Prover Create Master Secret
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverCreateCredentialReq(self, request, context):
    """Prover Create Credential Req
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverStoreCredential(self, request, context):
    """Prover Store Credential
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverGetCredential(self, request, context):
    """Prover Get Credential
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverGetCredentials(self, request, context):
    """Prover Get Credentials
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverSeachCredentials(self, request, context):
    """Prover Seach Credentials
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverFetchCredentials(self, request, context):
    """Prover Fetch Credentials
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverCloseCredentialsSearch(self, request, context):
    """Prover Close Credentials Search
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverGetCredentialsForProofReq(self, request, context):
    """Prover Get Credentials For Proof Req
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverSearchCredentialsForProofReq(self, request, context):
    """Prover Search Credentials For Proof Req
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverFetchCredentialsForProofReq(self, request, context):
    """Prover Fetch Credentials For Proof Req
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverCloseCredentialsSearchForProofReq(self, request, context):
    """Prover Close Credentials Search For Proof Req
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProverCreateProof(self, request, context):
    """Prover Create Proof
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifierVerifyProof(self, request, context):
    """Verifier Verify Proof
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateRevocationState(self, request, context):
    """Create Revocation State
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRevocationState(self, request, context):
    """Update Revocation State
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnoncredsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IssuerCreateSchema': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerCreateSchema,
          request_deserializer=identitylayer__pb2.IssuerCreateSchemaRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerCreateSchemaResponse.SerializeToString,
      ),
      'IssuerCreateAndStoreCredentialDef': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerCreateAndStoreCredentialDef,
          request_deserializer=identitylayer__pb2.IssuerCreateAndStoreCredentialDefRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerCreateAndStoreCredentialDefResponse.SerializeToString,
      ),
      'IssuerCreateAndStoreRevocReg': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerCreateAndStoreRevocReg,
          request_deserializer=identitylayer__pb2.IssuerCreateAndStoreRevocRegRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerCreateAndStoreRevocRegResponse.SerializeToString,
      ),
      'IssuerCreateCredentialOffer': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerCreateCredentialOffer,
          request_deserializer=identitylayer__pb2.IssuerCreateCredentialOfferRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerCreateCredentialOfferResponse.SerializeToString,
      ),
      'IssuerCreateCredential': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerCreateCredential,
          request_deserializer=identitylayer__pb2.IssuerCreateCredentialRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerCreateCredentialResponse.SerializeToString,
      ),
      'IssuerRevokeCredential': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerRevokeCredential,
          request_deserializer=identitylayer__pb2.IssuerRevokeCredentialRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerRevokeCredentialResponse.SerializeToString,
      ),
      'IssuerMergeRevocationRegistryDeltas': grpc.unary_unary_rpc_method_handler(
          servicer.IssuerMergeRevocationRegistryDeltas,
          request_deserializer=identitylayer__pb2.IssuerMergeRevocationRegistryDeltasRequest.FromString,
          response_serializer=identitylayer__pb2.IssuerMergeRevocationRegistryDeltasResponse.SerializeToString,
      ),
      'ProverCreateMasterSecret': grpc.unary_unary_rpc_method_handler(
          servicer.ProverCreateMasterSecret,
          request_deserializer=identitylayer__pb2.ProverCreateMasterSecretRequest.FromString,
          response_serializer=identitylayer__pb2.ProverCreateMasterSecretResponse.SerializeToString,
      ),
      'ProverCreateCredentialReq': grpc.unary_unary_rpc_method_handler(
          servicer.ProverCreateCredentialReq,
          request_deserializer=identitylayer__pb2.ProverCreateCredentialReqRequest.FromString,
          response_serializer=identitylayer__pb2.ProverCreateCredentialReqResponse.SerializeToString,
      ),
      'ProverStoreCredential': grpc.unary_unary_rpc_method_handler(
          servicer.ProverStoreCredential,
          request_deserializer=identitylayer__pb2.ProverStoreCredentialRequest.FromString,
          response_serializer=identitylayer__pb2.ProverStoreCredentialResponse.SerializeToString,
      ),
      'ProverGetCredential': grpc.unary_unary_rpc_method_handler(
          servicer.ProverGetCredential,
          request_deserializer=identitylayer__pb2.ProverGetCredentialRequest.FromString,
          response_serializer=identitylayer__pb2.ProverGetCredentialResponse.SerializeToString,
      ),
      'ProverGetCredentials': grpc.unary_unary_rpc_method_handler(
          servicer.ProverGetCredentials,
          request_deserializer=identitylayer__pb2.ProverGetCredentialsRequest.FromString,
          response_serializer=identitylayer__pb2.ProverGetCredentialsResponse.SerializeToString,
      ),
      'ProverSeachCredentials': grpc.unary_unary_rpc_method_handler(
          servicer.ProverSeachCredentials,
          request_deserializer=identitylayer__pb2.ProverSeachCredentialsRequest.FromString,
          response_serializer=identitylayer__pb2.ProverSeachCredentialsResponse.SerializeToString,
      ),
      'ProverFetchCredentials': grpc.unary_unary_rpc_method_handler(
          servicer.ProverFetchCredentials,
          request_deserializer=identitylayer__pb2.ProverFetchCredentialsRequest.FromString,
          response_serializer=identitylayer__pb2.ProverFetchCredentialsResponse.SerializeToString,
      ),
      'ProverCloseCredentialsSearch': grpc.unary_unary_rpc_method_handler(
          servicer.ProverCloseCredentialsSearch,
          request_deserializer=identitylayer__pb2.ProverCloseCredentialsSearchRequest.FromString,
          response_serializer=identitylayer__pb2.ProverCloseCredentialsSearchResponse.SerializeToString,
      ),
      'ProverGetCredentialsForProofReq': grpc.unary_unary_rpc_method_handler(
          servicer.ProverGetCredentialsForProofReq,
          request_deserializer=identitylayer__pb2.ProverGetCredentialsForProofReqRequest.FromString,
          response_serializer=identitylayer__pb2.ProverGetCredentialsForProofReqResponse.SerializeToString,
      ),
      'ProverSearchCredentialsForProofReq': grpc.unary_unary_rpc_method_handler(
          servicer.ProverSearchCredentialsForProofReq,
          request_deserializer=identitylayer__pb2.ProverSearchCredentialsForProofReqRequest.FromString,
          response_serializer=identitylayer__pb2.ProverSearchCredentialsForProofReqResponse.SerializeToString,
      ),
      'ProverFetchCredentialsForProofReq': grpc.unary_unary_rpc_method_handler(
          servicer.ProverFetchCredentialsForProofReq,
          request_deserializer=identitylayer__pb2.ProverFetchCredentialsForProofReqRequest.FromString,
          response_serializer=identitylayer__pb2.ProverFetchCredentialsForProofReqResponse.SerializeToString,
      ),
      'ProverCloseCredentialsSearchForProofReq': grpc.unary_unary_rpc_method_handler(
          servicer.ProverCloseCredentialsSearchForProofReq,
          request_deserializer=identitylayer__pb2.ProverCloseCredentialsSearchForProofReqRequest.FromString,
          response_serializer=identitylayer__pb2.ProverCloseCredentialsSearchForProofReqResponse.SerializeToString,
      ),
      'ProverCreateProof': grpc.unary_unary_rpc_method_handler(
          servicer.ProverCreateProof,
          request_deserializer=identitylayer__pb2.ProverCreateProofRequest.FromString,
          response_serializer=identitylayer__pb2.ProverCreateProofResponse.SerializeToString,
      ),
      'VerifierVerifyProof': grpc.unary_unary_rpc_method_handler(
          servicer.VerifierVerifyProof,
          request_deserializer=identitylayer__pb2.VerifierVerifyProofRequest.FromString,
          response_serializer=identitylayer__pb2.VerifierVerifyProofResponse.SerializeToString,
      ),
      'CreateRevocationState': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRevocationState,
          request_deserializer=identitylayer__pb2.CreateRevocationStateRequest.FromString,
          response_serializer=identitylayer__pb2.CreateRevocationStateResponse.SerializeToString,
      ),
      'UpdateRevocationState': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateRevocationState,
          request_deserializer=identitylayer__pb2.UpdateRevocationStateRequest.FromString,
          response_serializer=identitylayer__pb2.UpdateRevocationStateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.AnoncredsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WalletServiceStub(object):
  """Wallet Service Start
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateNewWallet = channel.unary_unary(
        '/identitylayer.WalletService/CreateNewWallet',
        request_serializer=identitylayer__pb2.NewWalletDefinition.SerializeToString,
        response_deserializer=identitylayer__pb2.CreateWalletErrorCode.FromString,
        )
    self.OpenWallet = channel.unary_unary(
        '/identitylayer.WalletService/OpenWallet',
        request_serializer=identitylayer__pb2.OpenWalletDefinition.SerializeToString,
        response_deserializer=identitylayer__pb2.OpenWalletHandle.FromString,
        )
    self.CloseWallet = channel.unary_unary(
        '/identitylayer.WalletService/CloseWallet',
        request_serializer=identitylayer__pb2.CloseWalletHandle.SerializeToString,
        response_deserializer=identitylayer__pb2.CloseWalletStatus.FromString,
        )
    self.DeleteWallet = channel.unary_unary(
        '/identitylayer.WalletService/DeleteWallet',
        request_serializer=identitylayer__pb2.DeleteWalletDefinition.SerializeToString,
        response_deserializer=identitylayer__pb2.DeleteWalletConfirmation.FromString,
        )
    self.ExportWallet = channel.unary_unary(
        '/identitylayer.WalletService/ExportWallet',
        request_serializer=identitylayer__pb2.ExportWalletDefinition.SerializeToString,
        response_deserializer=identitylayer__pb2.ExportWalletConfirmation.FromString,
        )
    self.ImportWallet = channel.unary_unary(
        '/identitylayer.WalletService/ImportWallet',
        request_serializer=identitylayer__pb2.ImportWalletDefinition.SerializeToString,
        response_deserializer=identitylayer__pb2.ImportWalletConfirmation.FromString,
        )
    self.GenerateWalletKey = channel.unary_unary(
        '/identitylayer.WalletService/GenerateWalletKey',
        request_serializer=identitylayer__pb2.GenerateWalletKeyDefinition.SerializeToString,
        response_deserializer=identitylayer__pb2.GenerateWalletKeyConfirmation.FromString,
        )


class WalletServiceServicer(object):
  """Wallet Service Start
  """

  def CreateNewWallet(self, request, context):
    """Create wallet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenWallet(self, request, context):
    """Open Wallet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseWallet(self, request, context):
    """Close Wallet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteWallet(self, request, context):
    """Delete Wallet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExportWallet(self, request, context):
    """Export Wallet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportWallet(self, request, context):
    """Import Wallet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateWalletKey(self, request, context):
    """Generate Wallet Key
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateNewWallet': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNewWallet,
          request_deserializer=identitylayer__pb2.NewWalletDefinition.FromString,
          response_serializer=identitylayer__pb2.CreateWalletErrorCode.SerializeToString,
      ),
      'OpenWallet': grpc.unary_unary_rpc_method_handler(
          servicer.OpenWallet,
          request_deserializer=identitylayer__pb2.OpenWalletDefinition.FromString,
          response_serializer=identitylayer__pb2.OpenWalletHandle.SerializeToString,
      ),
      'CloseWallet': grpc.unary_unary_rpc_method_handler(
          servicer.CloseWallet,
          request_deserializer=identitylayer__pb2.CloseWalletHandle.FromString,
          response_serializer=identitylayer__pb2.CloseWalletStatus.SerializeToString,
      ),
      'DeleteWallet': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteWallet,
          request_deserializer=identitylayer__pb2.DeleteWalletDefinition.FromString,
          response_serializer=identitylayer__pb2.DeleteWalletConfirmation.SerializeToString,
      ),
      'ExportWallet': grpc.unary_unary_rpc_method_handler(
          servicer.ExportWallet,
          request_deserializer=identitylayer__pb2.ExportWalletDefinition.FromString,
          response_serializer=identitylayer__pb2.ExportWalletConfirmation.SerializeToString,
      ),
      'ImportWallet': grpc.unary_unary_rpc_method_handler(
          servicer.ImportWallet,
          request_deserializer=identitylayer__pb2.ImportWalletDefinition.FromString,
          response_serializer=identitylayer__pb2.ImportWalletConfirmation.SerializeToString,
      ),
      'GenerateWalletKey': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateWalletKey,
          request_deserializer=identitylayer__pb2.GenerateWalletKeyDefinition.FromString,
          response_serializer=identitylayer__pb2.GenerateWalletKeyConfirmation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.WalletService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BlobStorageServiceStub(object):
  """`blob storage` services
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OpenReader = channel.unary_unary(
        '/identitylayer.BlobStorageService/OpenReader',
        request_serializer=identitylayer__pb2.OpenReaderRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.OpenReaderResponse.FromString,
        )
    self.OpenWriter = channel.unary_unary(
        '/identitylayer.BlobStorageService/OpenWriter',
        request_serializer=identitylayer__pb2.OpenWriterRequest.SerializeToString,
        response_deserializer=identitylayer__pb2.OpenWriterResponse.FromString,
        )


class BlobStorageServiceServicer(object):
  """`blob storage` services
  """

  def OpenReader(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenWriter(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlobStorageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OpenReader': grpc.unary_unary_rpc_method_handler(
          servicer.OpenReader,
          request_deserializer=identitylayer__pb2.OpenReaderRequest.FromString,
          response_serializer=identitylayer__pb2.OpenReaderResponse.SerializeToString,
      ),
      'OpenWriter': grpc.unary_unary_rpc_method_handler(
          servicer.OpenWriter,
          request_deserializer=identitylayer__pb2.OpenWriterRequest.FromString,
          response_serializer=identitylayer__pb2.OpenWriterResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identitylayer.BlobStorageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
