# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pairwise.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pairwise.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0epairwise.proto\"A\n\x17IsPairwiseExistsRequest\x12\x14\n\x0cWalletHandle\x18\x01 \x01(\x03\x12\x10\n\x08TheirDid\x18\x02 \x01(\t\"\'\n\x18IsPairwiseExistsResponse\x12\x0b\n\x03Res\x18\x01 \x01(\x08\"`\n\x15\x43reatePairwiseRequest\x12\x14\n\x0cWalletHandle\x18\x01 \x01(\x03\x12\x10\n\x08TheirDid\x18\x02 \x01(\t\x12\r\n\x05MyDid\x18\x03 \x01(\t\x12\x10\n\x08Metadata\x18\x04 \x01(\t\"+\n\x16\x43reatePairwiseResponse\x12\x11\n\tErrorCode\x18\x01 \x01(\x03\"+\n\x13ListPairwiseRequest\x12\x14\n\x0cWalletHandle\x18\x01 \x01(\x03\",\n\x14ListPairwiseResponse\x12\x14\n\x0cPairwiseList\x18\x01 \x03(\t\"<\n\x12GetPairwiseRequest\x12\x14\n\x0cWalletHandle\x18\x01 \x01(\x03\x12\x10\n\x08TheirDid\x18\x02 \x01(\t\"/\n\x13GetPairwiseResponse\x12\x18\n\x10PairwiseInfoJson\x18\x01 \x01(\t\"V\n\x1aSetPairwiseMetadataRequest\x12\x14\n\x0cWalletHandle\x18\x01 \x01(\x03\x12\x10\n\x08TheirDid\x18\x02 \x01(\t\x12\x10\n\x08MetaData\x18\x03 \x01(\t\"0\n\x1bSetPairwiseMetadataResponse\x12\x11\n\tErrorCode\x18\x01 \x01(\x03\x62\x06proto3')
)




_ISPAIRWISEEXISTSREQUEST = _descriptor.Descriptor(
  name='IsPairwiseExistsRequest',
  full_name='IsPairwiseExistsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WalletHandle', full_name='IsPairwiseExistsRequest.WalletHandle', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TheirDid', full_name='IsPairwiseExistsRequest.TheirDid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=83,
)


_ISPAIRWISEEXISTSRESPONSE = _descriptor.Descriptor(
  name='IsPairwiseExistsResponse',
  full_name='IsPairwiseExistsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Res', full_name='IsPairwiseExistsResponse.Res', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=124,
)


_CREATEPAIRWISEREQUEST = _descriptor.Descriptor(
  name='CreatePairwiseRequest',
  full_name='CreatePairwiseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WalletHandle', full_name='CreatePairwiseRequest.WalletHandle', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TheirDid', full_name='CreatePairwiseRequest.TheirDid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MyDid', full_name='CreatePairwiseRequest.MyDid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Metadata', full_name='CreatePairwiseRequest.Metadata', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=222,
)


_CREATEPAIRWISERESPONSE = _descriptor.Descriptor(
  name='CreatePairwiseResponse',
  full_name='CreatePairwiseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='CreatePairwiseResponse.ErrorCode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=267,
)


_LISTPAIRWISEREQUEST = _descriptor.Descriptor(
  name='ListPairwiseRequest',
  full_name='ListPairwiseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WalletHandle', full_name='ListPairwiseRequest.WalletHandle', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=312,
)


_LISTPAIRWISERESPONSE = _descriptor.Descriptor(
  name='ListPairwiseResponse',
  full_name='ListPairwiseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PairwiseList', full_name='ListPairwiseResponse.PairwiseList', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=358,
)


_GETPAIRWISEREQUEST = _descriptor.Descriptor(
  name='GetPairwiseRequest',
  full_name='GetPairwiseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WalletHandle', full_name='GetPairwiseRequest.WalletHandle', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TheirDid', full_name='GetPairwiseRequest.TheirDid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=420,
)


_GETPAIRWISERESPONSE = _descriptor.Descriptor(
  name='GetPairwiseResponse',
  full_name='GetPairwiseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PairwiseInfoJson', full_name='GetPairwiseResponse.PairwiseInfoJson', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=469,
)


_SETPAIRWISEMETADATAREQUEST = _descriptor.Descriptor(
  name='SetPairwiseMetadataRequest',
  full_name='SetPairwiseMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WalletHandle', full_name='SetPairwiseMetadataRequest.WalletHandle', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TheirDid', full_name='SetPairwiseMetadataRequest.TheirDid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MetaData', full_name='SetPairwiseMetadataRequest.MetaData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=557,
)


_SETPAIRWISEMETADATARESPONSE = _descriptor.Descriptor(
  name='SetPairwiseMetadataResponse',
  full_name='SetPairwiseMetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='SetPairwiseMetadataResponse.ErrorCode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=607,
)

DESCRIPTOR.message_types_by_name['IsPairwiseExistsRequest'] = _ISPAIRWISEEXISTSREQUEST
DESCRIPTOR.message_types_by_name['IsPairwiseExistsResponse'] = _ISPAIRWISEEXISTSRESPONSE
DESCRIPTOR.message_types_by_name['CreatePairwiseRequest'] = _CREATEPAIRWISEREQUEST
DESCRIPTOR.message_types_by_name['CreatePairwiseResponse'] = _CREATEPAIRWISERESPONSE
DESCRIPTOR.message_types_by_name['ListPairwiseRequest'] = _LISTPAIRWISEREQUEST
DESCRIPTOR.message_types_by_name['ListPairwiseResponse'] = _LISTPAIRWISERESPONSE
DESCRIPTOR.message_types_by_name['GetPairwiseRequest'] = _GETPAIRWISEREQUEST
DESCRIPTOR.message_types_by_name['GetPairwiseResponse'] = _GETPAIRWISERESPONSE
DESCRIPTOR.message_types_by_name['SetPairwiseMetadataRequest'] = _SETPAIRWISEMETADATAREQUEST
DESCRIPTOR.message_types_by_name['SetPairwiseMetadataResponse'] = _SETPAIRWISEMETADATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IsPairwiseExistsRequest = _reflection.GeneratedProtocolMessageType('IsPairwiseExistsRequest', (_message.Message,), dict(
  DESCRIPTOR = _ISPAIRWISEEXISTSREQUEST,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:IsPairwiseExistsRequest)
  ))
_sym_db.RegisterMessage(IsPairwiseExistsRequest)

IsPairwiseExistsResponse = _reflection.GeneratedProtocolMessageType('IsPairwiseExistsResponse', (_message.Message,), dict(
  DESCRIPTOR = _ISPAIRWISEEXISTSRESPONSE,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:IsPairwiseExistsResponse)
  ))
_sym_db.RegisterMessage(IsPairwiseExistsResponse)

CreatePairwiseRequest = _reflection.GeneratedProtocolMessageType('CreatePairwiseRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEPAIRWISEREQUEST,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:CreatePairwiseRequest)
  ))
_sym_db.RegisterMessage(CreatePairwiseRequest)

CreatePairwiseResponse = _reflection.GeneratedProtocolMessageType('CreatePairwiseResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEPAIRWISERESPONSE,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:CreatePairwiseResponse)
  ))
_sym_db.RegisterMessage(CreatePairwiseResponse)

ListPairwiseRequest = _reflection.GeneratedProtocolMessageType('ListPairwiseRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTPAIRWISEREQUEST,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:ListPairwiseRequest)
  ))
_sym_db.RegisterMessage(ListPairwiseRequest)

ListPairwiseResponse = _reflection.GeneratedProtocolMessageType('ListPairwiseResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTPAIRWISERESPONSE,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:ListPairwiseResponse)
  ))
_sym_db.RegisterMessage(ListPairwiseResponse)

GetPairwiseRequest = _reflection.GeneratedProtocolMessageType('GetPairwiseRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPAIRWISEREQUEST,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:GetPairwiseRequest)
  ))
_sym_db.RegisterMessage(GetPairwiseRequest)

GetPairwiseResponse = _reflection.GeneratedProtocolMessageType('GetPairwiseResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPAIRWISERESPONSE,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:GetPairwiseResponse)
  ))
_sym_db.RegisterMessage(GetPairwiseResponse)

SetPairwiseMetadataRequest = _reflection.GeneratedProtocolMessageType('SetPairwiseMetadataRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETPAIRWISEMETADATAREQUEST,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:SetPairwiseMetadataRequest)
  ))
_sym_db.RegisterMessage(SetPairwiseMetadataRequest)

SetPairwiseMetadataResponse = _reflection.GeneratedProtocolMessageType('SetPairwiseMetadataResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETPAIRWISEMETADATARESPONSE,
  __module__ = 'pairwise_pb2'
  # @@protoc_insertion_point(class_scope:SetPairwiseMetadataResponse)
  ))
_sym_db.RegisterMessage(SetPairwiseMetadataResponse)


# @@protoc_insertion_point(module_scope)
